### ISSUE TITLE
Extending builtin prototypes is considered to be a bad practice

### ISSUE THREAD

**Issue by TimothyGu** [underscorediscovery/realtime-multiplayer-in-html5#13]
See https://github.com/underscorediscovery/realtime-multiplayer-in-html5/blob/00af50dd57baa29f30809925881a624bc50234f1/game.core.js#L180

Instead, one might write the function as

```js
function fixed(num, n = 3) {
  return parseFloat(num.toFixed(n));
}

// ...

return { x:fixed(a.x+b.x), y:fixed(a.y+b.y) };

**Comment by ruby0x1** [comment]
Thanks, I'm aware. 
This project was just example code so I opted for that at the time (back in 2012).
