### ISSUE TITLE
would you accept a PR to convert to es modules + data oriented design?

### ISSUE THREAD

**Issue by mreinstein** [underscorediscovery/realtime-multiplayer-in-html5#14]
I have a working port of this code which basically does 3 things:

* switches the code from object oriented syntax to data oriented (all functions in `game-core.js` accept a game-core object.)
* in server side, replace `requestAnimationFrame` with `setTimeout` (removes need for polyfill)
* switches to es modules for both the client and server

benefits:
* no more `this` peppered all over the code
* no more need to put references to `window` or `global` into the code that runs across browser

I realize this is a super old project, and it's oriented towards learning, but maybe this change would be welcome? If so, happy to send a PR.

**Comment by ruby0x1** [comment]
Hi, while I appreciate the intent, this is 8+ years old and is what it is. You're welcome to leave a link to your version if people are interested in that, they can use that. Thanks!

**Comment by mreinstein** [comment]
totally understandable, given this repo is intimately tied to an explainer article. Thanks for the quick reply! ❤️ 

btw it might be nice to just update the npm deps. Would keep the code identical, but keep this valuable learning resource alive well on modern node.

**Comment by mreinstein** [comment]
for anyone that's interested, here is my fork which:
* switches game.core from object oriented to a data oriented approach
* uses es modules everywhere 
* moves number functions to not extend the built in number type

https://github.com/mreinstein/realtime-multiplayer-in-html5

happy to accept pull requests on this! Some ideas:
* adopting a light ECS (entity component system) could be really great
* further decouple logic out of the game-core module
