### ISSUE TITLE
The demo is not available

### ISSUE THREAD

**Issue by Kolyunya** [underscorediscovery/realtime-multiplayer-in-html5#6]
The [demo](http://underscorediscovery.aws.af.cm/?debug) is unavailable at the moment.

**Comment by drasive** [comment]
It seems like the [demo](http://underscorediscovery.aws.af.cm/?debug) is down again.

**Comment by underscorediscovery** [comment]
@drasive try again, thanks for reporting. 

I also just turned up the number of instances and gave them a lot more memory, so hopefully it will stop going down.
